services:
  db:
    image: postgres:18-alpine
    container_name: agents_tasks_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agents_tasks_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: agents_tasks_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/agents_tasks_db
      - SECRET_KEY=yoursecretkeychangethisinproduction2024
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/code
    restart: unless-stopped

volumes:
  postgres_data:
